---
# ACR_NAME=bwsandboxacr
# USER_NAME="00000000-0000-0000-0000-000000000000"
# PASSWORD=$(az acr login --name $ACR_NAME --expose-token --output tsv --query accessToken)
# helm registry login $ACR_NAME.azurecr.io \
#   --username $USER_NAME \
#   --password $PASSWORD
#
# vault kv put secret/azure/acr/sandbox \
#   username=${USER_NAME} \
#   password=${PASSWORD} \
#   registry=${ACR_NAME}.azurecr.io
{{- $name := "acr-sandbox" }}
{{- $keys := list "username" "password" "registry" "registry_path" }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $name }}
spec:
  provider: vault
  secretObjects:
    - secretName: {{ $name }}
      type: Opaque
      data:
{{- range $k, $v := $keys }}
      - objectName: {{ $v }}
        key: {{ $v }}
{{- end }}
  parameters:
    roleName: acr_sandbox_reader
    objects: |
{{- range $k, $v := $keys }}
      - objectName: {{ $v }}
        secretPath: secret/data/azure/acr/sandbox
        secretKey: {{ $v }}
{{- end }}

