---
# ACR_NAME=bwsandboxacr
# USER_NAME="00000000-0000-0000-0000-000000000000"
# PASSWORD=$(az acr login --name $ACR_NAME --expose-token --output tsv --query accessToken)
# helm registry login $ACR_NAME.azurecr.io \
#   --username $USER_NAME \
#   --password $PASSWORD
#
# vault kv put secret/azure/acr/sandbox \
#   username=${USER_NAME} \
#   password=${PASSWORD} \
#   registry=${ACR_NAME}.azurecr.io
{{- $name := "acr-sandbox" }}
{{- $registry_keys := list "registry" "registry_path" }}
{{- $sp_keys := list "ARM_CLIENT_ID" "ARM_CLIENT_SECRET" "ARM_SUBSCRIPTION_ID" "ARM_TENANT_ID" }}
{{- $combined_keys := concat $registry_keys $sp_keys }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $name }}
spec:
  provider: vault
  secretObjects:
    - secretName: {{ $name }}
      type: Opaque
      data:
{{- range $k, $v := $combined_keys }}
      - objectName: {{ $v }}
        key: {{ $v }}
{{- end }}
  parameters:
    roleName: acr_sandbox_reader
    objects: |
{{- range $k, $v := $registry_keys }}
      - objectName: {{ $v }}
        secretPath: secret/data/azure/acr/sandbox
        secretKey: {{ $v }}
{{- end }}
{{- range $k, $v := $sp_keys }}
      - objectName: {{ $v }}
        secretPath: secret/data/azure/sp/infra
        secretKey: {{ $v }}
{{- end }}

