---
{{- $name := "acr-sandbox" }}
{{- $keys := list "username" "secret" "password" }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $name }}
spec:
  provider: vault
  secretObjects:
    - secretName: {{ $name }}
      type: Opaque
      data:
{{- range $k, $v := $keys }}
      - objectName: {{ $v }}
        key: {{ $v }}
{{- end }}
  parameters:
    roleName: acr_sandbox_reader
    objects: |
{{- range $k, $v := $keys }}
      - objectName: {{ $v }}
        secretPath: secret/data/azure/acr/sandbox
        secretKey: {{ $v }}
{{- end }}

