apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: flavor-helm-template
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: git_repo
      - name: git_ref_type
        value: branches
      - name: git_version
      - name: helm_image
        value: ""
      # helm repos to add in the form of json arrayy with fields for name and url
      - name: helm_repo_add
        value: "[]"
      - name: csi_class
        value: ""
    steps:
    - - name: default
        template: default
        arguments:
          parameters:
          # TODO: need some sort of helm repo add args
          # deploy-secrets-store-csi-driver-km5hk-1040760463: Error: no repository definition for https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts. Please add the missing repos via 'helm repo add'
            {{- include "parameter.from.input" "helm_image"    | nindent 13 }}
            {{- include "parameter.from.input" "helm_repo_add" | nindent 13 }}
            {{- include "parameter.from.input" "git_repo"      | nindent 13 }}
            {{- include "parameter.from.input" "git_ref_type"  | nindent 13 }}
            {{- include "parameter.from.input" "git_version"   | nindent 13 }}
            {{- include "parameter.from.input" "csi_class"     | nindent 13 }}

  - name: default
    inputs:
      parameters:
      - name: git_repo
      - name: git_ref_type
      - name: git_version
      - name: helm_image
      - name: helm_repo_add
      - name: csi_class
      artifacts:
      - name: git
        path: /tmp/src
        git:
          repo: '{{`{{ inputs.parameters.git_repo }}`}}'
          revision: '{{`{{ inputs.parameters.git_version }}`}}'
    volumes:
      - name: secrets
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "{{`{{ inputs.parameters.csi_class }}`}}"
    container:
      workingDir: /tmp/src
      image: '{{`{{ inputs.parameters.helm_image }}`}}'
      envFrom:
        - secretRef:
            name: "{{`{{ inputs.parameters.csi_class }}`}}"
      volumeMounts:
        - name: secrets
          mountPath: /secrets
      command: [/bin/bash, -lc]
      args:
        - |
          set -e
          {{- include "acr.login" . | nindent 10 }}

          set -x
          # check for helm repo add
          if [ "[]" != "{{`{{ inputs.parameters.helm_repo_add }}`}}" ]; then
            echo '{{`{{inputs.parameters.helm_repo_add}}`}}' \
              | jq '.[] | .name, .url' -r \
              | xargs -n2 helm repo add ${1} ${2}
          fi

          # download helm dependencies
          helm dependency build
          # lint
          helm lint .
          if [ "tags" = "{{`{{ inputs.parameters.git_ref_type }}`}}" ]; then
            helm package .
            file=$(ls | grep tgz)
            helm push ./${file} "oci://${registry}${registry_path}"
          fi

