apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: flavor-ansible-template
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  entrypoint: main
  templates:
{{ range $k, $v := .Values.flavors.custom_dockerfile }}
  - name: {{ $k }}
    inputs:
      parameters:
      - name: git_repo
      - name: git_version
      - name: upstream_repo
      - name: upstream_tag
      # suffix to add to the end of our tag ie ${git_version}-${upstream_tag_suffix} which is usually platform or platform+version
      - name: tag_suffix
      - name: repo_name
      - name: platform
      - name: ansible_destroy
        value: 'true'
      - name: ansible_args
        value: |
          [{"platform": "linux/amd64", "ansible_extra_args": ""}]
    dag:
      tasks:
      - name: build-image
        templateRef:
          name: kaniko-template
          template: main
        withParam: "{{`{{inputs.parameters.ansible_args}}`}}"
        arguments:
          parameters:
          - name: git_repo
            value: "{{`{{ inputs.parameters.git_repo }}`}}"
          - name: git_version
            value: "{{`{{ inputs.parameters.git_version }}`}}"
          - name: repo_name
            value: '{{`{{ inputs.parameters.repo_name }}`}}'
          - name: tag
            {{ if eq $k "tags" }}
            value: "{{`{{ inputs.parameters.git_version }}`}}{{`{{inputs.parameters.tag_suffix}}`}}-{{`{{=sprig.replace('/','_',item.platform)}}`}}"
            {{ else }}
            value: "latest{{`{{inputs.parameters.tag_suffix}}`}}-{{`{{=sprig.replace('/','_',item.platform)}}`}}"
            {{- end }}
          - name: push
            value: {{ $v.push | quote }}
          - name: runtime_platform
            value: "{{`{{item.platform}}`}}"
          - name: ansible_destroy
            value: "{{ `{{ inputs.parameters.ansible_destroy }}`}}"
          - name: dockerfile
            value: |
              FROM --platform={{`{{item.platform}}`}} {{`{{ inputs.parameters.upstream_repo }}`}}:{{`{{ inputs.parameters.upstream_tag }}`}}-{{`{{ inputs.parameters.platform}}`}} as builder
              COPY . .
              RUN ansible-galaxy install -r requirements.yml
              RUN ansible-playbook playbook.yml -e '{{`{{ item.ansible_extra_args }}`}}'
              RUN {{`{{=sprig.ternary('ansible-destroy','echo skipping destroy',inputs.parameters.ansible_destroy == "true")}}`}}

      {{- if eq $k "tags" }}
      {{- $combine_args := dict "template" $k "depends" "build-image" "platform_json" `{{ inputs.parameters.ansible_args }}` "platform_json_pluck" "platform" }}
      {{- include "combine-manifest" $combine_args | nindent 6 }}

      {{- end }}
{{- end }}
