apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: flavor-go-template
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  entrypoint: main
  templates:
{{ range $k, $v := list "branches" "tags" }}
  - name: {{ $v }}
    {{- include "go.parameters" . | nindent 4 }}
    steps:
    - - name: go-releaser
        template: go-releaser
        arguments:
          parameters:
            {{- include "parameter.from.input" "git_repo"                | nindent 12 }}
            {{- include "parameter.from.input" "git_version"             | nindent 12 }}
            {{- include "parameter.from.input" "vault_secrets_enabled"   | nindent 12 }}
            {{- include "parameter.from.input" "vault_env_secrets_paths" | nindent 12 }}
            {{- include "parameter.from.input" "vault_role"              | nindent 12 }}
            {{- include "parameter.from.input" "vault_issue_token"       | nindent 12 }}
            - name: image
              value: {{`{{ inputs.parameters.upstream_repo }}:{{ inputs.parameters.upstream_tag }}-{{ inputs.parameters.platform}}` | quote }}
            - name: git_ref_type
              value: {{ $v | quote }}

{{- end }}

  - name: go-releaser
    inputs:
      parameters:
        - name: git_repo
        - name: git_ref_type
        - name: git_version
        - name: image
        - name: vault_secrets_enabled
        - name: vault_env_secrets_paths
        - name: vault_role
        - name: vault_issue_token
      artifacts:
        - name: source-repo
          path: /src
          git:
            repo: "{{`{{ inputs.parameters.git_repo }}`}}"
            version: "{{`{{ inputs.parameters.git_version }}`}}"
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "{{`{{ inputs.parameters.vault_secrets_enabled }}`}}"
        vault.hashicorp.com/role: "{{`{{ inputs.parameters.vault_role }}`}}"
        vault.hashicorp.com/agent-cache-enable: "true"
        vault.hashicorp.com/agent-cache-listener-port: "8200"
        vault.hashicorp.com/agent-cache-use-auto-auth-token: force
    container:
      workingDir: /src
      image: "{{`{{ inputs.parameters.image }}`}}"
      command: [/bin/sh, -lc]
      args:
        - |
          goreleaser check

          {{- include "vault.secret.import.script" . | nindent 10 }}

          if [ "tags" = "{{`{{ inputs.parameters.git_ref_type }}`}}" ]; then
            git status
            goreleaser release
          else
            goreleaser build --snapshot
          fi

          ls -lh dist
