apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: flavor-go-template
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  entrypoint: main
  templates:
{{ range $k, $v := .Values.flavors.custom_dockerfile }}
  - name: {{ $k }}
    inputs:
      parameters:
      - name: git_repo
      - name: git_version
      - name: upstream_repo
      - name: upstream_tag
      - name: repo_name
      - name: platform
      - name: go_main_path
      - name: runtime_platforms
        value: [linux/amd64]
    dag:
      tasks:
      - name: build-image
        withParam: "{{`{{inputs.parameters.runtime_platforms}}`}}"
        templateRef:
          name: kaniko-template
          template: main
        arguments:
          parameters:
          - name: git_repo
            value: "{{`{{ inputs.parameters.git_repo }}`}}"
          - name: git_version
            value: "{{`{{ inputs.parameters.git_version }}`}}"
          - name: repo_name
            value: '{{`{{ inputs.parameters.repo_name }}`}}'
          - name: tag
            {{ if eq $k "tags" }}
            value: "{{`{{ inputs.parameters.git_version }}`}}-{{`{{inputs.parameters.platform}}`}}"
            {{ else }}
            value: "latest-{{`{{inputs.parameters.platform}}`}}"
            {{- end }}
          - name: push
            value: {{ $v.push | quote }}
          - name: runtime_platform
            value: "{{`{{item}}`}}"
          - name: dockerfile
            # platform sets the target architecture, will require 3 args then to build the image - https://docs.docker.com/engine/reference/builder/#from
            value: |
              FROM --platform={{`{{item}}`}} {{`{{ inputs.parameters.upstream_repo }}`}}:{{`{{ inputs.parameters.upstream_tag }}`}}-{{`{{ inputs.parameters.platform}}`}} as builder
              COPY . .
              RUN go build {{`{{ inputs.parameters.go_main_path}}`}}

      {{- if eq $k "tags" }}
      {{- $combine_args := dict "template" $k "depends" "build-image" }}
      {{- include "combine-manifest" $combine_args | nindent 6 }}
      {{- end }}
{{- end }}
