apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: flavor-ansible-template
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  entrypoint: main
  templates:
{{ range $k, $v := .Values.flavors.custom_dockerfile }}
  - name: {{ $k }}
    inputs:
      parameters:
      - name: git_repo
      - name: git_version
      - name: upstream_repo
      - name: upstream_tag
      # suffix to add to the end of our tag ie ${git_version}-${upstream_tag_suffix} which is usually platform or platform+version
      - name: tag_suffix
      - name: repo_name
      - name: platform
    dag:
      tasks:
      - name: build-image
        templateRef:
          name: kaniko-template
          template: main
        arguments:
          parameters:
          - name: git_repo
            value: "{{`{{ inputs.parameters.git_repo }}`}}"
          - name: git_version
            value: "{{`{{ inputs.parameters.git_version }}`}}"
          - name: repo_name
            value: '{{`{{ inputs.parameters.repo_name }}`}}'
          - name: tag
            {{ if eq $k "tags" }}
            value: "{{`{{ inputs.parameters.git_version }}`}}-{{`{{inputs.parameters.platform}}`}}"
            {{ else }}
            value: "latest-{{`{{inputs.parameters.platform}}`}}"
            {{- end }}
          - name: push
            value: {{ $v.push | quote }}
          - name: dockerfile
            value: |
              FROM {{`{{ inputs.parameters.upstream_repo }}`}}:{{`{{ inputs.parameters.upstream_tag }}`}}-{{`{{ inputs.parameters.platform}}`}} as builder
              COPY . .
              RUN ansible-galaxy install -r requirements.yml
              RUN ansible-playbook playbook.yml
              RUN ansible-destroy
{{- end }}
