apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: flavor-image-mirror-template
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  entrypoint: main
  templates:
{{ range $k, $v := .Values.flavors.mirror }}
  - name: {{ $k }}
    inputs:
      parameters:
        - name: git_repo
        - name: git_version
        - name: upstream_repo
        - name: upstream_tag
        - name: upstream_repo_name_override
          value: ""
        - name: repo_name
        - name: tag
          value: latest
    dag:
      tasks:
        - name: mirror-image
          arguments:
            parameters:
              - name: git_repo
                value: "{{`{{ inputs.parameters.git_repo }}`}}"
              - name: git_version
                value: "{{`{{ inputs.parameters.git_version }}`}}"
              - name: repo_name
                value: "{{`{{ inputs.parameters.repo_name }}`}}"
              - name: tag
                value: "{{`{{ inputs.parameters.tag }}`}}-{{`{{=sprig.default(inputs.parameters.upstream_repo, inputs.parameters.upstream_repo_name_override)}}`}}_{{`{{ inputs.parameters.upstream_tag }}`}}"
              - name: push
                value: {{ $v.push | quote }}
              - name: dockerfile
                value: |
                  FROM {{`{{ inputs.parameters.upstream_repo }}`}}:{{`{{ inputs.parameters.upstream_tag }}`}}
          templateRef:
            name: kaniko-template
            template: main
{{- end }}
