apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: flavor-go-template
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  entrypoint: main
  templates:
{{ range $k, $v := list "branches" "tags" }}
  - name: {{ $v }}
    {{- include "go.parameters" . | nindent 4 }}
    steps:
    - - name: go-releaser
        template: go-releaser
        arguments:
          parameters:
            {{- include "parameter.from.input" "git_repo"                | nindent 12 }}
            {{- include "parameter.from.input" "git_version"             | nindent 12 }}
            - name: image
              value: {{`{{ inputs.parameters.upstream_repo }}:{{ inputs.parameters.upstream_tag }}-{{ inputs.parameters.platform}}` | quote }}
            - name: git_ref_type
              value: {{ $v | quote }}

{{- end }}

  - name: go-releaser
    inputs:
      parameters:
        - name: git_repo
        - name: git_ref_type
        - name: git_version
        - name: image
      artifacts:
        - name: source-repo
          path: /src
          git:
            repo: "{{`{{ inputs.parameters.git_repo }}`}}"
            revision: "{{`{{ inputs.parameters.git_version }}`}}"
    volumes:
      - name: secrets
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: go-releaser
    container:
      workingDir: /src
      envFrom:
        - secretRef:
            name: go-releaser
      volumeMounts:
        - name: secrets
          mountPath: /secrets
      image: "{{`{{ inputs.parameters.image }}`}}"
      command: [/bin/sh, -lc]
      args:
        - |
          goreleaser check

          if [ "tags" = "{{`{{ inputs.parameters.git_ref_type }}`}}" ]; then
            git status
            goreleaser release
          else
            goreleaser build --snapshot
          fi
          exit_code=$?

          [ -d dist ] && ls -lh dist
          exit ${exit_code}

