apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: flavor-ansible-role-template
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: git_repo
      - name: git_version
      - name: upstream_repo
      - name: upstream_tag
      - name: platform
      - name: ansible_debug
        value: false
      - name: ansible_args
        value: |
          [{"platform": "linux/amd64", "ansible_extra_args": ""}]
    steps:
    - - name: ansible-role-test
        template: ansible-role-test
        withParam: "{{`{{inputs.parameters.ansible_args}}`}}"
        arguments:
          parameters:
            {{- include "parameter.from.input" "git_repo"        | nindent 12 }}
            {{- include "parameter.from.input" "git_version"     | nindent 12 }}
            {{- include "parameter.from.input" "ansible_debug"   | nindent 12 }}
            - name: ansible_extra_args
              value: "{{`{{ item.ansible_extra_args }}`}}"
            - name: image
              value: "{{`{{inputs.parameters.upstream_repo}}:{{inputs.parameters.upstream_tag}}-{{inputs.parameters.platform}}-{{=sprig.replace('/', '_', item.platform)}}`}}"

  - name: ansible-role-test
    inputs:
      parameters:
      - name: git_repo
      - name: git_version
      - name: ansible_debug
        value: false
      - name: ansible_extra_args
      - name: image
      artifacts:
      - name: source-repo
        path: /src
        git:
          repo: "{{`{{ inputs.parameters.git_repo }}`}}"
          revision: "{{`{{ inputs.parameters.git_version }}`}}"
    container:
      workingDir: /src
      image: "{{`{{ inputs.parameters.image }}`}}"
      command: [/bin/sh, -lc]
      args:
        - |
          uname -m
          {{`{{=sprig.ternary('ansible -m setup localhost','echo Skipping Host Debug',inputs.parameters.ansible_debug == "true")}}`}}
          [ -f meta/requirements.yml ] && ansible-galaxy install -r meta/requirements.yml || echo "Skipping Role Dependency Download: No requirements.yml Found"
          ansible-playbook test.yml

