apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: flavor-terraform-template
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: git_repo
      - name: git_ref_type
        value: branches
      - name: git_version
      - name: terraform_image
        value: "{{ $.Values.flavors.terraform.image }}"
      - name: vault_secrets_enabled
        value: false
      - name: vault_env_secrets_paths
        value: "[]"
      - name: vault_role
        value: "default"
      # issues token for the same role to use in terraform - good for vault provider
      - name: vault_issue_token
        value: false
    steps:
    - - name: plan
        template: tf-plan
        arguments:
          parameters:
            {{- include "parameter.from.input" "terraform_image"         | nindent 13 }}
            {{- include "parameter.from.input" "git_repo"                | nindent 13 }}
            {{- include "parameter.from.input" "git_ref_type"            | nindent 13 }}
            {{- include "parameter.from.input" "git_version"             | nindent 13 }}
            {{- include "parameter.from.input" "vault_secrets_enabled"   | nindent 13 }}
            {{- include "parameter.from.input" "vault_env_secrets_paths" | nindent 13 }}
            {{- include "parameter.from.input" "vault_role"              | nindent 13 }}
            {{- include "parameter.from.input" "vault_issue_token"       | nindent 13 }}
  - name: tf-plan
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "{{`{{ inputs.parameters.vault_secrets_enabled }}`}}"
        vault.hashicorp.com/role: "{{`{{ inputs.parameters.vault_role }}`}}"
        vault.hashicorp.com/agent-cache-enable: "true"
        vault.hashicorp.com/agent-cache-listener-port: "8200"
        vault.hashicorp.com/agent-cache-use-auto-auth-token: force
    inputs:
      parameters:
      - name: git_repo
      - name: git_ref_type
      - name: git_version
      - name: terraform_image
      - name: vault_secrets_enabled
      - name: vault_env_secrets_paths
      - name: vault_role
      - name: vault_issue_token
      artifacts:
      - name: git
        path: /tmp/src
        git:
          repo: '{{`{{ inputs.parameters.git_repo }}`}}'
          revision: '{{`{{ inputs.parameters.git_version }}`}}'
    container:
      podSpecPatch: '{"shareProcessNamespace": true}'
      workingDir: /tmp/src
      image: '{{`{{ inputs.parameters.terraform_image }}`}}'
      command: [/bin/sh, -lc]
      args:
        - |
          {{- include "vault.secret.import.script" . | nindent 10}}

          terraform init
          terraform plan

          # apply only on tags!
          if [ "tags" = "{{`{{ inputs.parameters.git_ref_type }}`}}" ]; then
            terraform apply -auto-approve
          fi

