---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: go-releaser
spec:
  provider: vault
  secretObjects:
    - secretName: go-releaser
      type: Opaque
      data:
        - objectName: github_token
          key: GITHUB_TOKEN
  parameters:
    roleName: go_releaser_reader
    objects: |
      - objectName: github_token
        secretPath: secret/data/go_releaser
        secretKey: GITHUB_TOKEN
