apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: kaniko-template
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: git_repo
      - name: git_version
      - name: repo_name
      - name: tag
      - name: dockerfile
      - name: runtime_platform
      - name: push
        value: "--no-push" # empty if we want to push
      artifacts:
      - name: git
        path: /tmp/src
        git:
          repo: '{{`{{ inputs.parameters.git_repo }}`}}'
          revision: '{{`{{ inputs.parameters.git_version }}`}}'
      - name: dockerfile
        path: /tmp/Dockerfile
        raw:
          data: |
            # source: kaniko build template
            {{`{{inputs.parameters.dockerfile}}`}}
    volumes:
    - name: quay
      csi:
        driver: 'secrets-store.csi.k8s.io'
        readOnly: true
        volumeAttributes:
          secretProviderClass: quay
    container:
      image: {{ .Values.kaniko.image }}
      command: [/kaniko/executor]
      args: ["--dockerfile=/tmp/Dockerfile",
             "--context=dir:///tmp/src",
             "--destination={{`{{inputs.parameters.repo_name}}`}}:{{`{{inputs.parameters.tag}}`}}",
             "--customPlatform={{`{{inputs.parameters.runtime_platform}}`}}",
             "{{`{{inputs.parameters.push}}`}}"
            ]
      volumeMounts:
        - name: quay
          mountPath: /kaniko/.docker
