# TODO: fill this out
# https://github.com/estesp/manifest-tool
# $ ./manifest-tool push from-args \
#    --platforms linux/amd64,linux/arm,linux/arm64 \
#    --template foo/bar-ARCH:v1 \
#    --target foo/bar:v1
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: manifest-template
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: repo_name
      # base tag to use ie
      # tag-upstream_upstreamtag
      - name: tag
      - name: runtime_platforms
        value: []
    volumes:
    - name: kaniko-secret
      secret:
        secretName: {{ .Values.kaniko.secret }}
        items:
          - key: .dockerconfigjson
            path: config.json
    container:
#      image: {{ .Values.manifest.image }}
#      command: [/manifest-tool]
      image: alpine
      command: [echo]
      args: [
            push,
            from-args,
            "--platforms",
            # TODO: fix this is yielding push from-args --platforms ["linux/arm64","linux/amd64","linux/arm"] --template quay.io/bradfordwagner/base:latest-alpin
        #e_3.12-OS_ARCH --target quay.io/bradfordwagner/base:latest-alpine_3.12
            # [] are wrong
            "{{`{{=sprig.join(',', inputs.parameters.runtime_platforms)}}`}}",
            "--template",
            "{{`{{inputs.parameters.repo_name }}`}}:{{`{{inputs.parameters.tag}}`}}-OS_ARCH",
            "--target",
            "{{`{{inputs.parameters.repo_name}}`}}:{{`{{inputs.parameters.tag}}`}}"
            ]
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
