---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: quay
spec:
  provider: vault
  parameters:
    roleName: quay_reader
    objects: |
      - objectName: config.json
        secretPath: secret/data/quay
        secretKey: ".dockerconfigjson"
