---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sp-infra
spec:
  provider: vault
  secretObjects:
    - secretName: sp-infra
      type: Opaque
      data:
      - objectName: arm_subscription_id
        key: ARM_SUBSCRIPTION_ID
      - objectName: arm_client_id
        key: ARM_CLIENT_ID
      - objectName: arm_client_secret
        key: ARM_CLIENT_SECRET
      - objectName: arm_tenant_id
        key: ARM_TENANT_ID
  parameters:
    roleName: vault_policy_scaffolding
    objects: |
      - objectName: arm_subscription_id
        secretPath: secret/data/azure/sp/infra
        secretKey: ARM_SUBSCRIPTION_ID
      - objectName: arm_client_id
        secretPath: secret/data/azure/sp/infra
        secretKey: ARM_CLIENT_ID
      - objectName: arm_client_secret
        secretPath: secret/data/azure/sp/infra
        secretKey: ARM_CLIENT_SECRET
      - objectName: arm_tenant_id
        secretPath: secret/data/azure/sp/infra
        secretKey: ARM_TENANT_ID
